/* eslint-disable react/jsx-no-comment-textnodes */
import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";
import Model from "@/components/Model";
import ColorfulString from "@/components/ColorfulString";
const inter = Inter({ subsets: ["latin"] });
import { AnimatePresence, motion } from "framer-motion";
import GlowEffect from "@/components/Card";

// eslint-disable-next-line react/jsx-no-comment-textnodes
export default function Home() {
    const variant = {
        hidden: {
            scale: 0.8,
            opacity: 0,
        },
        visible: {
            scale: 1,
            opacity: 1,
            transition: {
                delay: 0.4,
                duration: 0.4,
            },
        },
    };
    return (
        <>
            <Head>
                <title>Create Next App</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <meta
                    name="viewport"
                    content="width=device-width, initial-scale=1"
                />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <main className={`${styles.main} ${inter.className}`}>
                {/* <Model /> */}
                <div className={styles.container}>
                    <div className={styles.left}>
                        <AnimatePresence key={1}>
                            <div className={styles.hero_container}>
                                <motion.div
                                    className={styles.left_col_top}
                                    initial="hidden"
                                    animate="visible"
                                    variants={{
                                        hidden: {
                                            scale: 0.8,
                                            opacity: 0,
                                        },
                                        visible: {
                                            scale: 1,
                                            opacity: 1,
                                            transition: {
                                                delay: 0.4,
                                                duration: 0.4,
                                            },
                                        },
                                    }}
                                >
                                    <h5 className={styles.intro_hero}>
                                        Hi all. I am
                                    </h5>
                                    <h1 className={styles.hero}>
                                        Nguyen Duc Bao
                                    </h1>
                                    <h3 className={styles.job}>
                                        &gt; Front-end developer
                                    </h3>
                                </motion.div>
                            </div>
                            <div className={styles.welcome}>
                                <div className={styles.comment}>
                                    <motion.p
                                        initial="hidden"
                                        animate="visible"
                                        variants={{
                                            hidden: {
                                                x: "-100px",
                                                opacity: 0,
                                            },
                                            visible: {
                                                x: 0,
                                                opacity: 1,
                                                transition: {
                                                    delay: 0.4,
                                                    duration: 0.4,
                                                },
                                            },
                                        }}
                                    >
                                        //{" "}
                                    </motion.p>
                                    <div>
                                        <motion.p
                                            initial="hidden"
                                            animate="visible"
                                            variants={{
                                                hidden: {
                                                    x: "100px",
                                                    opacity: 0,
                                                },
                                                visible: {
                                                    x: 0,
                                                    opacity: 1,
                                                    transition: {
                                                        delay: 0.4,
                                                        duration: 0.4,
                                                    },
                                                },
                                            }}
                                        >
                                            {" "}
                                            write the code below to continue:
                                        </motion.p>
                                    </div>
                                </div>
                                <div className={styles.comment}>
                                    <motion.p
                                        initial="hidden"
                                        animate="visible"
                                        variants={{
                                            hidden: {
                                                x: "-100px",
                                                opacity: 0,
                                            },
                                            visible: {
                                                x: 0,
                                                opacity: 1,
                                                transition: {
                                                    delay: 0.4,
                                                    duration: 0.4,
                                                },
                                            },
                                        }}
                                    >
                                        {" "}
                                        //
                                    </motion.p>
                                    <div>
                                        <motion.p
                                            initial="hidden"
                                            animate="visible"
                                            variants={{
                                                hidden: {
                                                    x: "100px",
                                                    opacity: 0,
                                                },
                                                visible: {
                                                    x: 0,
                                                    opacity: 1,
                                                    transition: {
                                                        delay: 0.4,
                                                        duration: 0.4,
                                                    },
                                                },
                                            }}
                                        >
                                            {" "}
                                            you can also see it on my Github
                                            page
                                        </motion.p>
                                    </div>
                                </div>
                                <ColorfulString />
                            </div>
                        </AnimatePresence>
                    </div>

                    <div className={styles.right}>
                        <GlowEffect />
                    </div>
                </div>
            </main>
        </>
    );
}
