/* eslint-disable react/jsx-no-comment-textnodes */
import Head from "next/head";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";

import ColorfulString from "@/components/ColorfulString";
const inter = Inter({ subsets: ["latin"] });
import { AnimatePresence, motion } from "framer-motion";
import GlowEffect from "@/components/Card";
import { Row } from "antd";
import { useState } from "react";
import { useIsMedium, useIsSmall } from "@/utils/useMediaQuery";

// eslint-disable-next-line react/jsx-no-comment-textnodes
export default function Home() {
    const [showContent, setShowContent] = useState(false); // State to control content visibility
    const [inputValue, setInputValue] = useState(""); // State to store input value

    const handleChange = (e: any) => {
        const value = e.target.value;
        setInputValue(value);

        // Show content when input value is "explore"
        setShowContent(value.toLowerCase() === "explore");
    };
    const isMobile = true;

    const fadeTopBottom = {
        initial: { opacity: 0, y: 30 },
        animate: {
            opacity: 1,
            y: 0,
            transition: {
                delay: 0.4,
                duration: 1.0,
            },
        },
    };
    const fadeLeftRight = {
        initial: { opacity: 0, x: -50 },
        animate: {
            opacity: 1,
            x: 0,

            transition: {
                delay: 0.4,
                duration: 1.0, // Increase the duration for slower animation
            },
        },
    };
    const fadeRightLeft = {
        initial: { opacity: 1, x: "calc(100vw / 4)" },
        animate: {
            opacity: 1,
            x: 0,
            transition: {
                delay: 0.4,
                duration: 0.5, // Increase the duration for slower animation
            },
        },
    };
    console.log(isMobile);
    const leftAnimation = isMobile ? fadeTopBottom : fadeRightLeft; // Use the fadeTopBottom variant for mobile screens
    const rightAnimation = isMobile ? fadeTopBottom : fadeLeftRight;
    return (
        <>
            <Head>
                <title>Create Next App</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <meta
                    name="viewport"
                    content="width=device-width, initial-scale=1"
                />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <main className={`${styles.main} ${inter.className}`}>
                {/* <Model /> */}
                <div className={styles.container}>
                    <motion.div
                        variants={leftAnimation}
                        initial="initial"
                        animate={"animate"} // Animate left side when showContent is true
                        className={styles.left}
                    >
                        <AnimatePresence key={1}>
                            <div className={styles.hero_container}>
                                <motion.div
                                    className={styles.left_col_top}
                                    initial="hidden"
                                    animate="visible"
                                    variants={{
                                        hidden: {
                                            scale: 0.8,
                                            opacity: 0,
                                        },
                                        visible: {
                                            scale: 1,
                                            opacity: 1,
                                            transition: {
                                                delay: 0.4,
                                                duration: 0.4,
                                            },
                                        },
                                    }}
                                >
                                    <h5 className={styles.intro_hero}>
                                        Hi all. I&apos;m a&nbsp;
                                    </h5>
                                    <h1 className={styles.hero}>
                                        Nguyen Duc Bao
                                    </h1>
                                    <h3 className={styles.job}>
                                        &gt;{" "}
                                        <span
                                            className={`${styles.typewriter} ${styles.thick}`}
                                        ></span>
                                    </h3>
                                </motion.div>
                            </div>
                            <div className={styles.welcome}>
                                <div className={styles.comment}>
                                    <motion.p
                                        initial="hidden"
                                        animate="visible"
                                        variants={{
                                            hidden: {
                                                x: "-100px",
                                                opacity: 0,
                                            },
                                            visible: {
                                                x: 0,
                                                opacity: 1,
                                                transition: {
                                                    delay: 0.4,
                                                    duration: 0.4,
                                                },
                                            },
                                        }}
                                    >
                                        //{" "}
                                    </motion.p>
                                    <div>
                                        <motion.p
                                            initial="hidden"
                                            animate="visible"
                                            variants={{
                                                hidden: {
                                                    x: "100px",
                                                    opacity: 0,
                                                },
                                                visible: {
                                                    x: 0,
                                                    opacity: 1,
                                                    transition: {
                                                        delay: 0.4,
                                                        duration: 0.4,
                                                    },
                                                },
                                            }}
                                        >
                                            {" "}
                                            write the code below to continue:
                                        </motion.p>
                                    </div>
                                </div>
                                <div className={styles.comment}>
                                    <motion.p
                                        initial="hidden"
                                        animate="visible"
                                        variants={{
                                            hidden: {
                                                x: "-100px",
                                                opacity: 0,
                                            },
                                            visible: {
                                                x: 0,
                                                opacity: 1,
                                                transition: {
                                                    delay: 0.4,
                                                    duration: 0.4,
                                                },
                                            },
                                        }}
                                    >
                                        {" "}
                                        //
                                    </motion.p>
                                    <div>
                                        <motion.p
                                            initial="hidden"
                                            animate="visible"
                                            variants={{
                                                hidden: {
                                                    x: "100px",
                                                    opacity: 0,
                                                },
                                                visible: {
                                                    x: 0,
                                                    opacity: 1,
                                                    transition: {
                                                        delay: 0.4,
                                                        duration: 0.4,
                                                    },
                                                },
                                            }}
                                        >
                                            {" "}
                                            you can also see it on my Github
                                            page
                                        </motion.p>
                                    </div>
                                </div>
                                <ColorfulString />
                                <Row style={{ alignItems: "center" }}>
                                    <div className={styles.label}>{`>`}</div>
                                    <input
                                        className={styles.input}
                                        type="text"
                                        placeholder="explore"
                                        maxLength={10}
                                        value={inputValue}
                                        onChange={handleChange}
                                    />
                                </Row>
                            </div>
                        </AnimatePresence>
                    </motion.div>

                    <motion.div
                        variants={rightAnimation}
                        initial="initial"
                        animate={showContent ? "animate" : "initial"} // Animate left side when showContent is true
                        className={styles.right}
                    >
                        <GlowEffect />
                    </motion.div>
                </div>
            </main>
        </>
    );
}
